name: nmr
channels:
  - conda-forge
  - bioconda
  - jmrohwer
  - defaults
dependencies:
  - numpy
  - scipy
  - ipykernel
  - matplotlib=3.8.4
  - nmrpy
  - rdkit=2024.03.5
  - xlsxwriter
  - pandas=2.1.4
  - pyarrow
  - jupyter
  - openpyxl
  - py3Dmol
